### ISSUE TITLE
Windows操作系统中无法直接运行ts-node

### ISSUE THREAD

**Issue by LinkTechTips** [Ericple/openscope-project#1]
如题，Windows操作系统中无法直接运行ts-node，会报错，可以通过全局安装解决问题，但我认为这并不是一个好的解决方案

参考这个 StackOverflow [讨论](https://stackoverflow.com/questions/44764004/ts-node-is-not-recognized-as-an-internal-or-external-command-operable-program).
> 我不建议在您自己的模块中依赖全局安装的 ts-node，因为如果你这样做，那么安装你的模块的任何人都需要全局安装 ts-node（仅仅一个普通的 npm install 是不够的）然后如果两个模块需要全局安装 ts-node 之类的东西，你可能就会遇到版本冲突的问题。

解决方法：建议在 package.json 中定义

错误日志：
````bash
$ npm i && npm run start

up to date in 1s

> openscope-project@0.3.0 start
> npm run compile && npm run updateassets && npm run test


> openscope-project@0.3.0 compile
> tsc


> openscope-project@0.3.0 updateassets
> ts-node CopyAssets.ts

'ts-node' is not recognized as an internal or external command,
operable program or batch file.

````

**Comment by Ericple** [comment]
现已将ts-node和typescript加入devDependencies中，启动调试改为使用npx调用，感谢建议 :1st_place_medal:  @LinkTechTips
