### ISSUE TITLE
您好，想跟你交流一下

### ISSUE THREAD

**Issue by ghost** [Ericple/openscope-project#2]
你的邮箱我发不过去……所以只能发在这里了
以下原文：
看到你开发的OpenScope了，我也在开发类似的控制软件，主要是我看不惯es丑陋的Ui，我没有跨平台的需求所以我是使用imgui+c++作为技术栈。
因为VATSIM繁杂的程序我并不准备推送到VATSIM而是普通的Legacy FSD，但是我在尝试解析EuroScope的handoff协议的时候发现他的handoff的包很牛马，我想请问一下你有了结果有关fsd中交接牌子的协议规范是怎样的么！感激不尽！

**Comment by Ericple** [comment]
你好！

有关FSD通信的问题，建议你放弃自己抓包，而转向相关项目找PDU包解决问题。
鉴于你使用的语言是C++，你可以参考[xpilot-project](https://github.com/xpilot-project/xpilot)，你可能需要的资料在该项目的路径为：`client\src\fsd`。

希望这个回答对你有所帮助。

**Comment by ghost** [comment]
你好！

非常感谢您的帮助，我在该项目中找到了相关的协议方式
此外，如果有需要的可以在这个网站中查找部分的FSD协议https://fsd-doc.norrisng.ca/site/index.html
可惜这个网站中并没有类似于管制交接之类的协议，如果需要管制协议可以按照上面说偶的去xpilot-project查看

感激不尽！
